config/routes.rb
Rails.application.routes.draw do
  root to: "favourites#index"

  get "sign_in"  => "sessions#new"
  get "sign_out" => "sessions#destroy"
  resource :otp_secret, only: [:new, :create]
  resource :session, only: [:create, :new, :destroy]

  %w[aoc board env deeds magic pam play prefectures premier risle ruby weight].each do |page|
    get page => "pages##{page}"
  end

  %w[petrol premier starling].each do |action|
    get "trmnl/#{action}", to: "trmnl##{action}"
  end

  namespace :pp do
    resources :prices, only: [:index]
    resources :stations, only: [:edit, :index, :show, :update]
    resources :sync_logs, only: [:index]
  end

  namespace :wk do
    resources :examples, except: [:show]
    resources :groups
    resources :kanas, only: [:edit, :index, :show, :update] do
      patch :quick_accent_update, on: :member
    end
    resources :kanjis, only: [:index, :show] do
      get :similar, on: :collection
    end
    resources :radicals, only: [:index, :show]
    resources :readings, only: [] do
      patch :quick_accent_update, on: :member
    end
    resources :verb_pairs, only: [:index]
    resources :vocabs, only: [:edit, :index, :show, :update]
  end

  resources :blogs
  resources :classifiers
  resources :constellations
  resources :favourites
  resources :flats
  resources :grammars do
    patch :quick_level_update, on: :member
    delete :remove_example, on: :member
    patch :add_group, on: :member
    patch :remove_group, on: :member
  end
  resources :grammar_groups
  resources :logins, only: [:index]
  resources :masses, except: [:show]
  resources :mass_events, except: [:show]
  resources :matches, only: [:index]
  resources :misas
  resources :notes
  resources :partnerships
  resources :people do
    get :checks, on: :collection
    get :match, on: :collection
    get :relationship, on: :member
    get :tree, on: :collection
    get :realm, on: :collection
    post :set_realm, on: :collection
  end
  resources :pictures
  resources :places do
    get :move, on: :member
    patch :shift, on: :member
  end
  resources :sounds, only: [:index, :show, :edit, :update] do
    patch :quick_level_update, on: :member
  end
  resources :stars
  resources :subscriptions
  resources :teams do
    get :stats, on: :member
  end
  resources :transactions, only: [:index] do
    post :upload, on: :collection
    patch :quick_approval_update, on: :member
  end
  resources :tutorials
  resources :users
end

app/models/star.rb
class Star < ApplicationRecord
  include Constrainable
  include Pageable
  include Remarkable
  include StarLink

  belongs_to :constellation, counter_cache: true

  MAX_NAME = 40
  MAX_SPECTRUM = 16
  ALPHA = /\A([01][0-9]|2[0-3])([0-5][0-9])([0-5][0-9])\z/
  DELTA = /\A(-)?([0-8][0-9])([0-5][0-9])([0-5][0-9])\z/
  BAYER = /\A([α-ωa-zA-z])([1-9]|10)?\z/
  GREEK = {alpha: "α", beta: "β", gamma: "γ", delta: "δ", epsilon: "ε", zeta: "ζ", eta: "η", theta: "θ", iota: "ι", kappa: "κ", lambda: "λ", mu: "μ", nu: "ν", xi: "ξ", omicron: "ο", pi: "π", rho: "ρ", sigma: "σ", tau: "τ", upsilon: "υ", phi: "φ", chi: "χ", psi: "ψ", omega: "ω"}

  before_validation :normalize_attributes

  validates :alpha, format: { with: ALPHA }
  validates :delta, format: { with: DELTA }
  validates :bayer, format: { with: BAYER }, uniqueness: { scope: :constellation_id }
  validates :name, presence: true, length: { maximum: MAX_NAME }, uniqueness: { case_sensitive: false }
  validates :spectrum, presence: true, length: { maximum: MAX_SPECTRUM }
  validates :wikipedia, presence: true, length: { maximum: MAX_NAME }, format: { with: /\A\S+\z/}, uniqueness: { case_sensitive: false }, allow_nil: true
  validates :components, numericality: { integer_only: true, greater_than: 0, less_than: 10 }
  validates :distance, numericality: { integer_only: true, greater_than: 0 }
  validates :luminosity, numericality: { greater_than_or_equal: 0.01, less_than: 100000000.0 }
  validates :magnitude, numericality: { greater_than: -2.0, less_than: 11.0 }
  validates :mass, numericality: { greater_than_or_equal: 0.01, less_than: 10000.0 }
  validates :radius, numericality: { greater_than_or_equal: 0.01, less_than: 10000.0 }
  validates :rank, numericality: { integer_only: true, greater_than: 0, less_than_or_equal: 100 }, uniqueness: true, allow_nil: true
  validates :temperature, numericality: { integer_only: true, greater_than: 0 }

  def self.search(params, path, opt={})
    matches = case params[:order]
    when "bayer"
      order(:bayer)
    when "components"
      order(components: :desc)
    when "distance"
      order(:distance)
    when "luminosity"
      order(luminosity: :desc)
    when "magnitude"
      order(:magnitude)
    when "mass"
      order(mass: :desc)
    when "radius"
      order(radius: :desc)
    when "rank"
      order(:rank)
    when "temperature"
      order(temperature: :desc)
    when "created"
      order(id: :desc)
    else
      order(:name)
    end
    matches = matches.includes(:constellation)
    if sql = cross_constraint(params[:q], %w{name note})
      matches = matches.where(sql)
    end
    if sql = numerical_constraint(params[:distance], :distance)
      matches = matches.where(sql)
    end
    if sql = numerical_constraint(params[:magnitude], :magnitude, digits: 2)
      matches = matches.where(sql)
    end
    if (cid = params[:constellation_id].to_i) > 0
      matches = matches.where(constellation_id: cid)
    end
    paginate(matches, params, path, opt)
  end

  def note_html = to_html(link_stars(note))

  def to_markdown(display, context)
    if context == self
      "**#{display}**"
    else
      "[#{display}](/stars/#{id})"
    end
  end

  private

  def normalize_attributes
    alpha&.gsub!(/\D+/, "")
    delta&.gsub!(/[^-0-9]+/, "")
    name&.squish!
    spectrum&.squish!
    self.bayer = "" if bayer.nil?
    bayer.lstrip!
    bayer.rstrip!
    if bayer.match(/\A([a-z][a-z]+)/i) && (letter = GREEK[$1.downcase.to_sym])
      bayer.sub!(/\A[a-z][a-z]+/i, letter)
    end
    if wikipedia.blank?
      self.wikipedia = nil
    else
      wikipedia.squish!
      wikipedia.gsub!(" ", "_")
    end
    self.note = "" if note.nil?
    note.lstrip!
    note.rstrip!
    note.gsub!(/([^\S\n]*\n){2,}[^\S\n]*/, "\n\n")
  end
end

app/controllers/stars_controller.rb
class StarsController < ApplicationController
  authorize_resource
  before_action :find_star, only: [:show, :edit, :update, :destroy]

  def index
    @stars = Star.search(params, stars_path, per_page: 10)
  end

  def new
    @star = Star.new
  end

  def create
    @star = Star.new(strong_params)
    if @star.save
      redirect_to @star
    else
      failure @star
      render :new, status: :unprocessable_content
    end
  end

  def update
    if @star.update(strong_params)
      redirect_to @star
    else
      failure @star
      render :edit, status: :unprocessable_content
    end
  end

  def destroy
    @star.destroy
    redirect_to stars_path
  end

  private

  def find_star
    @star = Star.find(params[:id])
  end

  def strong_params
    params.require(:star).permit(:alpha, :bayer, :components, :constellation_id, :delta, :distance, :luminosity, :magnitude, :mass, :name, :note, :radius, :rank, :spectrum, :temperature, :wikipedia)
  end
end

app/helpers/star_helper.rb
module StarHelper
  def star_search_order_menu(selected)
    opts = %w/name bayer components distance luminosity magnitude mass radius rank temperature/.map { |o| [t("star.#{o}"), o] }
    opts.push [t("created"), "created"]
    options_for_select(opts, selected)
  end

  def star_constellation_menu(star)
    opts = Constellation.order(:name).pluck(:name, :id)
    opts.unshift [t("select"), ""] if star.new_record?
    options_for_select(opts, star.constellation_id)
  end

  def star_constellation_search_menu
    opts = Constellation.order(:name).pluck(:name, :id)
    opts.unshift [t("any"), ""]
    options_for_select(opts, params[:constellation_id])
  end

  def star_right_ascension(alpha)
    if alpha&.match(Star::ALPHA)
      "#{$1}<sup>h</sup> #{$2}<sup>m</sup> #{$3}<sup>s</sup>".html_safe
    else
      alpha
    end
  end

  def star_declination(delta)
    if delta&.match(Star::DELTA)
      "#{$1}#{$2}° #{$3}′ #{$4}″"
    else
      delta
    end
  end

  def star_decimal(d)
    return "" if d.nil?
    if d >= 10000.0
      "%.1e" % d
    elsif d >= 9.99
      d.round.to_s
    elsif d >= 0.99
      "%.1f" % d
    else
      "%.2f" % d
    end
  end

  def star_integer(i)
    return "" if i.nil?
    if i >= 10000
      "%.1e" % i
    else
      i.to_s
    end
  end

  def star_constellation(star)
    return star.constellation&.name.to_s unless star.bayer.present?
    "#{star_bayer(star.bayer)} #{star.constellation&.iau}".html_safe
  end

  def star_bayer(bayer)
    return "" unless bayer&.match(Star::BAYER)
    "#{$1}#{$2 ? "<sup>#{$2}</sup>" : ""}".html_safe
  end

  def star_wikipedia(wikipedia)
    "https://en.wikipedia.org/wiki/#{wikipedia}"
  end
end

app/views/stars/_form.html.haml
:ruby
  inputs = [
    [:name,             t("star.name"),          :text,  maxlength: Star::MAX_NAME],
    [:constellation_id, t("star.constellation"), :select,  menu: star_constellation_menu(star)],
    [:alpha,            t("star.alpha"),         :text],
    [:delta,            t("star.delta"),         :text],
    [:bayer,            t("star.bayer"),         :text],
    [:components,       t("star.components"),    :text],
    [:distance,         t("star.distance"),      :text],
    [:luminosity,       t("star.luminosity"),    :text],
    [:magnitude,        t("star.magnitude"),     :text],
    [:mass,             t("star.mass"),          :text],
    [:radius,           t("star.radius"),        :text],
    [:rank,             t("star.rank"),          :text],
    [:spectrum,         t("star.spectrum"),      :text],
    [:temperature,      t("star.temperature"),   :text],
    [:wikipedia,        t("star.wikipedia"),     :text],
    [:note,             t("star.note"),          :area,  rows: 20],
  ]
= render "utils/crud/form", object: star, index: stars_path, inputs: inputs, title: title

app/views/stars/_star.html.haml
%tr
  %td= link_to star.name, star, "data-turbo-frame" => "_top"
  %td.text-center= link_to star_constellation(star), star.constellation
  %td.text-center= star.distance
  %td.text-center= star_decimal(star.magnitude)
  %td.text-center= star.rank
  %td.text-center= star_decimal(star.luminosity)
  %td.text-center= star_decimal(star.mass)
  %td.text-center= star_decimal(star.radius)
  %td.text-center= star.spectrum
  %td.text-center= star_integer(star.temperature)
  %td.text-center= star.components
  -# %td.text-center= star_right_ascension(star.alpha)
  -# %td.text-center= star_declination(star.delta)

app/views/stars/edit.html.haml
= render "utils/title", key: "star.edit"
= render "form", star: @star, title: t("star.edit")

app/views/stars/index.html.haml
:ruby
  lo = Sni::Layout.call(xl: [[2,2,2],[2,2]], md: [[3,3,3],[3,3]], xs: [[4,4,4],[4,4]])
  inputs = [
    [:q,                t("query"),              :text,   lo[0], placeholder: t("search"), autofocus: true],
    [:constellation_id, t("star.constellation"), :select, lo[1], menu: star_constellation_search_menu],
    [:order,            t("order"),              :select, lo[2], menu: star_search_order_menu(params[:order])],
    [:distance,         t("star.distance"),      :text,   lo[3], placeholder: t("star.distance")],
    [:magnitude,        t("star.magnitude"),     :text,   lo[4], placeholder: t("star.magnitude")],
  ]

= render "utils/title", key: "star.stars"

%section
  .header.text-center
    %h3= t("star.stars")
  .body
    = render "utils/search/form", index: stars_path, inputs: inputs
    = turbo_frame_tag :results, "data-turbo-action" => "advance" do
      %table{class: "table table-bordered table-sm mt-3"}
        %thead
          %tr
            %th= t("star.name")
            %th.text-center= t("star.abbrev.constellation")
            %th.text-center= t("star.abbrev.distance")
            %th.text-center= t("star.abbrev.magnitude")
            %th.text-center= t("star.rank")
            %th.text-center= t("star.abbrev.luminosity")
            %th.text-center= t("star.mass")
            %th.text-center= t("star.abbrev.radius")
            %th.text-center= t("star.abbrev.spectrum")
            %th.text-center= t("star.abbrev.temperature")
            %th.text-center= t("star.abbrev.components")
            -# %th.text-center= t("star.abbrev.alpha")
            -# %th.text-center= t("star.abbrev.delta")
        %tbody
          = render partial: "star", collection: @stars.matches
          = render "utils/pagination_links", pager: @stars, columns: 11
  - if can?(:create, Star)
    .footer
      = link_to t("constellation.constellations"), constellations_path, class: "green-btn"
      = link_to t("star.new"), new_star_path, class: "blue-btn"

app/views/stars/new.html.haml
= render "utils/title", key: "star.new"
= render "form", star: @star, title: t("star.new")

app/views/stars/show.html.haml
= render "utils/title", text: @star.name

.row
  %div{class: Sni::Center.call(lg: 10, xx: 8)}
    %section
      .header
        %h5.d-inline= @star.name
      .body
        %ul
          %li
            = "#{t('star.constellation')}:"
            = link_to star_constellation(@star), @star.constellation
          %li= "#{t('star.components')}: #{@star.components}"
          %li= "#{t('star.distance')}: #{@star.distance} #{t('star.unit.distance')}"
          %li= "#{t('star.luminosity')}: #{star_decimal(@star.luminosity)} #{t('star.unit.luminosity')}"
          %li= "#{t('star.magnitude')}: #{star_decimal(@star.magnitude)}"
          %li= "#{t('star.mass')}: #{star_decimal(@star.mass)} #{t('star.unit.mass')}"
          %li= "#{t('star.radius')}: #{star_decimal(@star.radius)} #{t('star.unit.radius')}"
          - if @star.rank.present?
            %li= "#{t('star.rank')}: #{@star.rank}"
          %li= "#{t('star.spectrum')}: #{@star.spectrum}"
          %li= "#{t('star.temperature')}: #{star_integer(@star.temperature)} #{t('star.unit.temperature')}"
          %li= "#{t('star.alpha')}: #{star_right_ascension(@star.alpha)}"
          %li= "#{t('star.delta')}: #{star_declination(@star.delta)}"
          - if @star.wikipedia.present?
            %li= link_to t("star.wikipedia"), star_wikipedia(@star.wikipedia), target: "_wikipedia"
        = @star.note_html
      .footer
        = link_to t("star.stars"), stars_path, class: "green-btn"
        = link_to t("constellation.constellations"), constellations_path, class: "green-btn"
        - if can?(:edit, Star)
          = link_to t("edit"), edit_star_path(@star), class: "blue-btn"