config/routes.rb
Rails.application.routes.draw do
  root to: "favourites#index"

  get "sign_in"  => "sessions#new"
  get "sign_out" => "sessions#destroy"
  resource :otp_secret, only: [:new, :create]
  resource :session, only: [:create, :new, :destroy]

  %w[aoc board env deeds magic pam play prefectures premier risle ruby weight].each do |page|
    get page => "pages##{page}"
  end

  %w[petrol premier starling].each do |action|
    get "trmnl/#{action}", to: "trmnl##{action}"
  end

  namespace :pp do
    resources :prices, only: [:index]
    resources :stations, only: [:edit, :index, :show, :update]
    resources :sync_logs, only: [:index]
  end

  namespace :wk do
    resources :examples, except: [:show]
    resources :groups
    resources :kanas, only: [:edit, :index, :show, :update] do
      patch :quick_accent_update, on: :member
    end
    resources :kanjis, only: [:index, :show] do
      get :similar, on: :collection
    end
    resources :radicals, only: [:index, :show]
    resources :readings, only: [] do
      patch :quick_accent_update, on: :member
    end
    resources :verb_pairs, only: [:index]
    resources :vocabs, only: [:edit, :index, :show, :update]
  end

  resources :blogs
  resources :classifiers
  resources :constellations
  resources :favourites
  resources :flats
  resources :grammars do
    patch :quick_level_update, on: :member
    delete :remove_example, on: :member
    patch :add_group, on: :member
    patch :remove_group, on: :member
  end
  resources :grammar_groups
  resources :logins, only: [:index]
  resources :masses, except: [:show]
  resources :mass_events, except: [:show]
  resources :matches, only: [:index]
  resources :misas
  resources :notes
  resources :partnerships
  resources :people do
    get :checks, on: :collection
    get :match, on: :collection
    get :relationship, on: :member
    get :tree, on: :collection
    get :realm, on: :collection
    post :set_realm, on: :collection
  end
  resources :pictures
  resources :places do
    get :move, on: :member
    patch :shift, on: :member
  end
  resources :sounds, only: [:index, :show, :edit, :update] do
    patch :quick_level_update, on: :member
  end
  resources :stars
  resources :subscriptions
  resources :teams do
    get :stats, on: :member
  end
  resources :transactions, only: [:index] do
    post :upload, on: :collection
    patch :quick_approval_update, on: :member
  end
  resources :tutorials
  resources :users
end

app/models/partnership.rb
class Partnership < ApplicationRecord
  include Constrainable
  include Pageable

  belongs_to :husband, class_name: "Person"
  belongs_to :wife, class_name: "Person"

  MIN_YR = Person::MIN_YR

  validates :divorce, numericality: { integer_only: true, greater_than_or_equal_to: MIN_YR }, allow_nil: true
  validates :husband_id, :wife_id, presence: true, numericality: { integer_only: true, greater_than: 0 }
  validates :husband_id, uniqueness: { scope: :wife_id }
  validates :realm, numericality: { integer_only: true, greater_than_or_equal_to: Person::MIN_REALM, less_than_or_equal_to: Person::MAX_REALM }
  validates :wedding, presence: true, numericality: { integer_only: true, greater_than_or_equal_to: MIN_YR }

  validate :years_must_make_sense
  validate :must_be_in_same_realm

  def self.search(params, path, opt={})
    matches = includes(:husband).includes(:wife).order(:wedding)
    if (constraint = numerical_constraint(params[:wedding], :wedding))
      matches = matches.where(constraint)
    end
    if (constraint = cross_constraint(params[:male], %w(last_name first_names known_as married_name), table: "husbands"))
      matches = matches.joins("INNER JOIN people AS husbands ON husbands.id = husband_id").where(constraint)
    end
    if (constraint = cross_constraint(params[:female], %w(last_name first_names known_as married_name), table: "wives"))
      matches = matches.joins("INNER JOIN people AS wives ON wives.id = wife_id").where(constraint)
    end
    matches = matches.where(realm: params[:realm].to_i)
    paginate(matches, params, path, opt)
  end

  def years(plus=false)
    if plus
      divorce ? "#{wedding_plus}-#{divorce_plus}" : wedding_plus
    else
      divorce ? "#{wedding}-#{divorce}" : wedding.to_s
    end
  end

  def wedding_plus
    year_plus(wedding, wedding_guess)
  end

  def divorce_plus
    divorce ? year_plus(divorce, divorce_guess) : nil
  end

  private

  def years_must_make_sense
    errors.add(:wedding, "can't be in the future") if wedding.present? && wedding > Date.today.year
    errors.add(:divorce, "can't be in the future") if divorce.present? && divorce > Date.today.year
    if wedding.present?
      errors.add(:divorce, "can't have divorced before getting married") if divorce.present? && wedding > divorce
      errors.add(:wedding, "can't marry before husband born") if husband.present? && husband.born >= wedding
      errors.add(:born, "can't be marry before wife born") if wife.present? && wife.born >= wedding
    end
  end

  def must_be_in_same_realm
    errors.add(:realm, "partners must be in same realm") if (husband.present? && husband.realm != realm) || (wife.present? && wife.realm != realm)
  end

  def year_plus(year, guess)
    "%d%s" % [year, guess ? "?" : ""]
  end
end

app/controllers/partnerships_controller.rb
class PartnershipsController < ApplicationController
  authorize_resource
  before_action :find_partnership, only: [:destroy, :edit, :show, :update]

  def index
    remember_last_search(partnerships_path)
    @partnerships = Partnership.search(params, partnerships_path)
  end

  def new
    person_id = params[:person_id].to_i
    if person_id > 0 && (person = Person.find_by(id: person_id))
      if person.male
        husband_id = person_id
      else
        wife_id = person_id
      end
    end
    @partnership = Partnership.new(husband_id: husband_id, wife_id: wife_id, realm: current_realm)
  end

  def create
    params[:partnership][:realm] = current_realm
    @partnership = Partnership.new(strong_params)
    if @partnership.save
      redirect_to @partnership
    else
      failure @partnership
      render :new, status: :unprocessable_content
    end
  end

  def update
    params[:partnership][:realm] = current_realm
    if @partnership.update(strong_params)
      redirect_to @partnership
    else
      failure @partnership
      render :edit, status: :unprocessable_content
    end
  end

  def destroy
    @partnership.destroy
    redirect_to partnerships_path
  end

  private

  def find_partnership
    @partnership = Partnership.find(params[:id])
  end

  def strong_params
    params.require(:partnership).permit(:divorce, :divorce_guess, :husband_id, :marriage, :realm, :wedding, :wedding_guess, :wife_id)
  end
end

app/helpers/partnership_helper.rb
module PartnershipHelper
  def partnership_husband_menu(partnership)
    partnership_spouse_menu(partnership, true)
  end

  def partnership_wife_menu(partnership)
    partnership_spouse_menu(partnership, false)
  end

  def partnership_spouse_menu(partnership, male)
    people = Person.order(:last_name, :first_names).where(male: male)
    people = people.where(realm: partnership.realm)
    people = people.where("born < ?", partnership.wedding) if partnership.wedding.present?
    people = people.all.map{ |p| [p.name(reversed: true, with_years: true), p.id] }
    people.unshift [t("select"), ""] if partnership.new_record?
    options_for_select(people, male ? partnership.husband_id : partnership.wife_id)
  end
end

app/views/partnerships/_form.html.haml
:ruby
  husband_source = "/people/match.json?gender=male"
  wife_source = "/people/match.json?gender=female"

:ruby
  inputs = [
    [:husband_id,    t("partnership.husband"),       :combo,  menu: partnership_husband_menu(partnership), model: "partnership", source: husband_source],
    [:wife_id,       t("partnership.wife"),          :combo,  menu: partnership_wife_menu(partnership), model: "partnership", source: wife_source],
    [:wedding,       t("partnership.wedding"),       :text,   maxlength: 4],
    [:wedding_guess, t("partnership.wedding_guess"), :check],
    [:divorce,       t("partnership.divorce"),       :text,   maxlength: 4],
    [:divorce_guess, t("partnership.divorce_guess"), :check],
    [:marriage,      t("partnership.marriage"),      :check],
  ]
= render "utils/crud/form", object: partnership, index: partnerships_path, inputs: inputs, title: title

app/views/partnerships/_partnership.html.haml
%tr
  %td= partnership.husband.name(reversed: true)
  %td= partnership.wife.name(reversed: true)
  %td= link_to partnership.wedding, partnership, "data-turbo-frame" => "_top"

app/views/partnerships/edit.html.haml
= render "utils/title", key: "partnership.edit"
= render "form", partnership: @partnership, title: t("partnership.edit")

app/views/partnerships/index.html.haml
:ruby
  lo = Sni::Layout.call(xs: [4,4,4])
  inputs = [
    [:male,    t("person.male"),         :text,   lo[0], size: 12],
    [:female,  t("person.female"),       :text,   lo[1], size: 12],
    [:wedding, t("partnership.wedding"), :text,   lo[2], size: 12],
  ]

= render "utils/title", key: "partnership.partnerships"

.row
  %div{class: Sni::Center.call(xl: 6, lg: 8, md: 10)}
    %section
      .header.text-center
        %h3= t("partnership.partnerships")
      .body
        = render "utils/search/form", index: partnerships_path, inputs: inputs
        = turbo_frame_tag :results, "data-turbo-action" => "advance" do
          %table{class: "table table-bordered table-sm mt-3"}
            %thead
              %tr
                %th= t("partnership.husband")
                %th= t("partnership.wife")
                %th= t("partnership.wedding")
            %tbody
              = render partial: "partnership", collection: @partnerships.matches
              = render "utils/pagination_links", pager: @partnerships, columns: 3
      .footer
        - if can?(:create, Partnership)
          = link_to t("partnership.new"), new_partnership_path, class: "blue-btn"
        = link_to t("help"), "#", class: "green-btn",
          "data-controller"      => "reveal",
          "data-reveal-id-value" => "help",
          "data-action"          => "reveal#toggle:prevent"
        = link_to t("person.people"), people_path, class: "green-btn"
        = link_to t("picture.pictures"), pictures_path, class: "green-btn"
        = link_to t("person.tree"), tree_people_path, class: "green-btn"
      .footer#help
        %h5= t("person.help.partnership")
        %ul
          %li
            = succeed(":") do
              %strong= t("person.male")
            Enter one or more terms to match the first, last or "known as" names of the male partner.
            Terms are case insensitive, don't have to be full names and order is not important.
            For example, a fairly specific search might be:
            %em "john smith"
            which would only find males that had names matching both those terms.
            In contrast, a less specific search example is:
            %em "jo sm"
            which would match John Smith but also Joe Smyth, Jon Dinsmore, and so on.
          %li
            = succeed(":") do
              %strong= t("person.female")
            Similar to
            %em= t("person.male")
            above but will constrain the female half of the partnership
            and also search the pre-marriage surname.
            For example, "coyle orr" will match women who were originally
            called "Coyle" then later called "Orr" (or the other way around).
          %li
            = succeed(":") do
              %strong= t("partnership.wedding")
            Enter a year (e.g. "1927"), a range (e.g. "1925-1935") or a limit (e.g. ">1900" or "<=1960") to
            constrain the start year of the partnership. For marriarges (the majority of the partnerships
            in this database) this is the wedding year.

app/views/partnerships/new.html.haml
= render "utils/title", key: "partnership.new"
= render "form", partnership: @partnership, title: t("partnership.new")

app/views/partnerships/show.html.haml
= render "utils/title", key: "partnership.partnership"

.row
  %div{class: Sni::Center.call(lg: 10, xl: 8)}
    %section
      .header.text-center
        %h3= t("partnership.partnership")
      .body
        %table{class: "table table-bordered table-sm"}
          %tbody
            %tr
              %th= t("partnership.husband")
              %td= link_to @partnership.husband.name, @partnership.husband
            %tr
              %th= t("partnership.wife")
              %td= link_to @partnership.wife.name, @partnership.wife
            %tr
              %th= t("partnership.wedding")
              %td= @partnership.wedding_plus
            - if @partnership.divorce.present?
              %tr
                %th= t("partnership.divorce")
                %td= @partnership.divorce_plus
            %tr
              %th= t("partnership.marriage")
              %td= t(@partnership.marriage ? "yes" : "no")
            %tr
              %th= t("person.realm")
              %td= t("person.realms")[@partnership.realm]
      - if can?(:manage, Partnership)
        .footer
          = link_to t("edit"), edit_partnership_path(@partnership), class: "blue-btn"
          = link_to t("person.people"), last_search(people_path), class: "green-btn"
          = link_to t("partnership.partnerships"), last_search(partnerships_path), class: "green-btn"