config/routes.rb
Rails.application.routes.draw do
  root to: "favourites#index"

  get "sign_in"  => "sessions#new"
  get "sign_out" => "sessions#destroy"
  resource :otp_secret, only: [:new, :create]
  resource :session, only: [:create, :new, :destroy]

  %w[aoc board env deeds magic pam play prefectures premier risle ruby weight].each do |page|
    get page => "pages##{page}"
  end

  %w[petrol premier starling].each do |action|
    get "trmnl/#{action}", to: "trmnl##{action}"
  end

  namespace :pp do
    resources :prices, only: [:index]
    resources :stations, only: [:edit, :index, :show, :update]
    resources :sync_logs, only: [:index]
  end

  namespace :wk do
    resources :examples, except: [:show]
    resources :groups
    resources :kanas, only: [:edit, :index, :show, :update] do
      patch :quick_accent_update, on: :member
    end
    resources :kanjis, only: [:index, :show] do
      get :similar, on: :collection
    end
    resources :radicals, only: [:index, :show]
    resources :readings, only: [] do
      patch :quick_accent_update, on: :member
    end
    resources :verb_pairs, only: [:index]
    resources :vocabs, only: [:edit, :index, :show, :update]
  end

  resources :blogs
  resources :classifiers
  resources :constellations
  resources :favourites
  resources :flats
  resources :grammars do
    patch :quick_level_update, on: :member
    delete :remove_example, on: :member
    patch :add_group, on: :member
    patch :remove_group, on: :member
  end
  resources :grammar_groups
  resources :logins, only: [:index]
  resources :masses, except: [:show]
  resources :mass_events, except: [:show]
  resources :matches, only: [:index]
  resources :misas
  resources :notes
  resources :partnerships
  resources :people do
    get :checks, on: :collection
    get :match, on: :collection
    get :relationship, on: :member
    get :tree, on: :collection
    get :realm, on: :collection
    post :set_realm, on: :collection
  end
  resources :pictures
  resources :places do
    get :move, on: :member
    patch :shift, on: :member
  end
  resources :sounds, only: [:index, :show, :edit, :update] do
    patch :quick_level_update, on: :member
  end
  resources :stars
  resources :subscriptions
  resources :teams do
    get :stats, on: :member
  end
  resources :transactions, only: [:index] do
    post :upload, on: :collection
    patch :quick_approval_update, on: :member
  end
  resources :tutorials
  resources :users
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  include Constrainable

  MAX_PAYEE = 50
  MAX_SOURCE = 40

  # The values are not arbitrary: they are the number of periods in 1 year and are used to calculate annual cost.
  enum :frequency, { monthly: 12, annually: 1, weekly: 52, daily: 365 }

  validates :amount, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :payee, presence: true, length: { maximum: MAX_PAYEE }, uniqueness: true
  validates :source, presence: true, length: { maximum: MAX_SOURCE }

  before_validation :canonicalize

  def self.search(params)
    matches = all
    if sql = cross_constraint(params[:payee], %w{payee})
      matches = matches.where(sql)
    end
    matches = matches.where(source: params[:source]) if params[:source].present?
    case params[:liable]
    when "joint"
      matches = matches.where("LOWER(source) LIKE ?", "%joint%")
    when "personal"
      matches = matches.where("LOWER(source) NOT LIKE ?", "%joint%")
    end
    matches.to_a.sort_by { |s| [-s.nominal_annual_cost, s.payee] }
  end
  
  def amount=(value)
    if value.is_a?(String)
      # Remove £ symbol and whitespace, then convert to float, multiply by 100 and round to get pennies.
      cleaned = value.gsub(/[£\s]/, '')
      if cleaned.match?(/^\d+(\.\d+)?$/)
        super((cleaned.to_f * 100).round)
      else
        super(value)
      end
    else
      super(value)
    end
  end

  def nominal_annual_cost
    @nominal_annual_cost ||= self.class.frequencies[frequency] * amount
  end

  def actual_annual_cost
    @actual_annual_cost ||= active? ? nominal_annual_cost : 0
  end

  def human_frequency
    I18n.t("activerecord.attributes.subscription.frequency.#{frequency}")
  end

  private

  def canonicalize
    payee&.squish!
    source&.squish!
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  authorize_resource
  before_action :find_subscription, only: [:show, :edit, :update, :destroy]

  def index
    @subscriptions = Subscription.search(params)
  end

  def new
    @subscription = Subscription.new
  end

  def create
    @subscription = Subscription.new(strong_params)
    if @subscription.save
      redirect_to @subscription
    else
      failure @subscription
      render :new, status: :unprocessable_content
    end
  end

  def update
    if @subscription.update(strong_params)
      redirect_to @subscription
    else
      failure @subscription
      render :edit, status: :unprocessable_content
    end
  end

  def destroy
    @subscription.destroy
    redirect_to subscriptions_path
  end

  private

  def find_subscription
    @subscription = Subscription.find(params[:id])
  end

  def strong_params
    params.require(:subscription).permit(:active, :amount, :frequency, :payee, :source)
  end
end

app/helpers/subscription_helper.rb
module SubscriptionHelper
  def sub_format_amount(pennies)
    return "" unless pennies.is_a?(Integer)
    "£#{sprintf('%.2f', pennies / 100.0)}"
  end

  def sub_frequency_menu(selected)
    opts = Subscription.frequencies.keys.map{|k| [I18n.t("activerecord.attributes.subscription.frequency.#{k}"), k]}
    options_for_select(opts, selected)
  end

  def sub_source_search_menu(selected)
    opts = Subscription.pluck(:source).uniq.compact.sort.map { |s| [s, s] }
    opts.unshift ["#{t('any')} #{t('subscription.source')}", ""]
    options_for_select(opts, selected)
  end

  def sub_liable_search_menu(selected)
    opts = I18n.t("subscription.liability").map{|k,v| [v, k]}
    options_for_select(opts, selected)
  end

  def sub_source_list
    Subscription.pluck(:source).uniq.compact.sort
  end
end

app/views/subscriptions/_form.html.haml
:ruby
  inputs = [
    [:payee,     t("subscription.payee"),     :text,   maxlength: Subscription::MAX_PAYEE],
    [:amount,    t("subscription.amount"),    :text,   value: sub_format_amount(subscription.amount)],
    [:frequency, t("subscription.frequency"), :select, menu: sub_frequency_menu(subscription.frequency)],
    [:source,    t("subscription.source"),    :list,   data: sub_source_list],
    [:active,    t("subscription.active"),    :check],
  ]
= render "utils/crud/form", object: subscription, index: subscriptions_path, inputs: inputs, title: title

app/views/subscriptions/_subscription.html.haml
%tr
  %td= link_to subscription.payee, subscription, "data-turbo-frame" => "_top"
  %td= subscription.source
  %td
    %span{class: ("text-decoration-line-through" unless subscription.active?)}= sub_format_amount(subscription.nominal_annual_cost)

app/views/subscriptions/edit.html.haml
= render "utils/title", key: "subscription.edit"
= render "form", subscription: @subscription, title: t("subscription.edit")

app/views/subscriptions/index.html.haml
:ruby
  lo = Sni::Layout.call(lg: [3,3,2], md: [3,4,3], xs: [4,4,4])
  inputs = [
    [:payee,  t("subscription.payee"),  :text,   lo[0], placeholder: t("subscription.payee")],
    [:source, t("subscription.source"), :select, lo[1], menu: sub_source_search_menu(params[:source])],
    [:liable, t("subscription.liable"), :select, lo[2], menu: sub_liable_search_menu(params[:liable])],
  ]

= render "utils/title", key: "subscription.subscriptions"

.row
  %div{class: Sni::Center.call(lg: 8, md: 10, sm: 12)}
    %section.mt-3
      .header.text-center
        %h3= t("subscription.subscriptions")
      .body
        = render "utils/search/form", index: subscriptions_path, inputs: inputs
        = turbo_frame_tag :results, "data-turbo-action" => "advance" do
          %table.table.table-bordered.table-sm.mt-3
            %thead
              %tr
                %th= t("subscription.payee")
                %th= t("subscription.source")
                %th= t("subscription.cost")
            %tbody
              = render partial: "subscription", collection: @subscriptions
              %tr
                %th.text-center{colspan: 2}
                %th= sub_format_amount(@subscriptions.map(&:actual_annual_cost).sum)
      - if can?(:create, Subscription)
        .footer
          = link_to t("subscription.new"), new_subscription_path, class: "blue-btn"

app/views/subscriptions/new.html.haml
= render "utils/title", key: "subscription.new"
= render "form", subscription: @subscription, title: t("subscription.new")

app/views/subscriptions/show.html.haml
= render "utils/title", text: @subscription.payee

.row
  %div{class: Sni::Center.call(lg: 8, md: 10, sm: 12)}
    %section
      .header.text-center
        %h3= @subscription.payee
      .body
        %table{class: "table table-bordered"}
          %tbody
            %tr
              %th= t("subscription.payee")
              %td= @subscription.payee
            %tr
              %th= t("subscription.source")
              %td= @subscription.source
            %tr
              %th= t("subscription.frequency")
              %td= @subscription.human_frequency
            %tr
              %th= t("subscription.amount")
              %td= sub_format_amount(@subscription.amount)
            %tr
              %th= t("subscription.cost")
              %td
                %span{class: ("text-decoration-line-through" unless @subscription.active?)}= sub_format_amount(@subscription.nominal_annual_cost)
      .footer
        = link_to t("subscription.subscriptions"), subscriptions_path, class: "green-btn"
        - if can?(:manage, Subscription)
          = link_to t("edit"), edit_subscription_path(@subscription), class: "blue-btn"