config/routes.rb
Rails.application.routes.draw do
  root to: "favourites#index"

  get "sign_in"  => "sessions#new"
  get "sign_out" => "sessions#destroy"
  resource :otp_secret, only: [:new, :create]
  resource :session, only: [:create, :new, :destroy]

  %w[aoc board env deeds magic pam play prefectures premier risle ruby weight].each do |page|
    get page => "pages##{page}"
  end

  %w[petrol premier starling].each do |action|
    get "trmnl/#{action}", to: "trmnl##{action}"
  end

  namespace :pp do
    resources :prices, only: [:index]
    resources :stations, only: [:edit, :index, :show, :update]
    resources :sync_logs, only: [:index]
  end

  namespace :wk do
    resources :examples, except: [:show]
    resources :groups
    resources :kanas, only: [:edit, :index, :show, :update] do
      patch :quick_accent_update, on: :member
    end
    resources :kanjis, only: [:index, :show] do
      get :similar, on: :collection
    end
    resources :radicals, only: [:index, :show]
    resources :readings, only: [] do
      patch :quick_accent_update, on: :member
    end
    resources :verb_pairs, only: [:index]
    resources :vocabs, only: [:edit, :index, :show, :update]
  end

  resources :blogs
  resources :classifiers
  resources :constellations
  resources :favourites
  resources :flats
  resources :grammars do
    patch :quick_level_update, on: :member
    delete :remove_example, on: :member
    patch :add_group, on: :member
    patch :remove_group, on: :member
  end
  resources :grammar_groups
  resources :logins, only: [:index]
  resources :masses, except: [:show]
  resources :mass_events, except: [:show]
  resources :matches, only: [:index]
  resources :misas
  resources :notes
  resources :partnerships
  resources :people do
    get :checks, on: :collection
    get :match, on: :collection
    get :relationship, on: :member
    get :tree, on: :collection
    get :realm, on: :collection
    post :set_realm, on: :collection
  end
  resources :pictures
  resources :places do
    get :move, on: :member
    patch :shift, on: :member
  end
  resources :sounds, only: [:index, :show, :edit, :update] do
    patch :quick_level_update, on: :member
  end
  resources :stars
  resources :subscriptions
  resources :teams do
    get :stats, on: :member
  end
  resources :transactions, only: [:index] do
    post :upload, on: :collection
    patch :quick_approval_update, on: :member
  end
  resources :tutorials
  resources :users
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  authorize_resource
  load_resource only: :quick_approval_update

  def index
    @transactions, @corrections = Transaction.search(params, transactions_path, per_page: 20)
    @averages = Transaction.averages(params)
  end

  def upload
    file = params[:file]
    upload_id = Transaction.last_upload_id + 1
    begin
      raise "no file" unless file.is_a?(ActionDispatch::Http::UploadedFile)
      raise "wrong file type (#{file.content_type})" unless file.content_type == "text/csv"
      flash[:notice] = Transaction.upload(file.path, upload_id)
    rescue => e
      flash[:alert] = e.message
    ensure
      redirect_to transactions_path(upload_id: upload_id)
    end
  end

  def quick_approval_update
    @transaction.toggle_approved
  end
end

app/helpers/transaction_helper.rb
module TransactionHelper
  def transaction_account_menu(selected)
    opts = Transaction::ACCOUNTS.values.uniq.map{|a| [t("transaction.accounts.#{a}"), a]}
    opts.unshift [t("any"), ""]
    options_for_select(opts, selected)
  end

  def transaction_category_menu(selected)
    opts = Transaction.pluck(:category).uniq.sort.map{|c| [c, c]}
    opts.unshift [t("any"), ""]
    options_for_select(opts, selected)
  end

  def transaction_order_menu(selected)
    opts = t("transaction.orders").map{|k,v| [v, k.to_s]}
    options_for_select(opts, selected)
  end

  def transaction_classifier_menu(selected)
    opts = Classifier.pluck(:name, :id)
    opts.unshift [t("transaction.approved"), -2]
    opts.unshift [t("transaction.unclassified"), -1]
    opts.unshift [t("any"), ""]
    options_for_select(opts, selected)
  end

  def transaction_date(date) = date.strftime("%y\u2011%m\u2011%d")
end

app/helpers/transactions_helper.rb
module TransactionsHelper
  def transaction_account_menu(selected)
    opts = Transaction::ACCOUNTS.values.map{|a| [t("transaction.accounts.#{a}"), a]}
    opts.unshift [t("any"), ""]
    options_for_select(opts, selected)
  end

  def transaction_category_menu(selected)
    opts = Transaction.pluck(:category).uniq.sort.map{|c| [c, c]}
    opts.unshift [t("any"), ""]
    options_for_select(opts, selected)
  end

  def transaction_order_menu(selected)
    opts = t("transaction.orders").map{|k,v| [v, k.to_s]}
    options_for_select(opts, selected)
  end

  def transaction_classifier_menu(selected)
    opts = Classifier.pluck(:name, :id)
    opts.unshift [t("transaction.unclassified"), -1]
    opts.unshift [t("any"), ""]
    options_for_select(opts, selected)
  end

  def css_background(transaction)
    if transaction.classifier
      "#" + transaction.classifier.color
    else
      "white"
    end
  end

  def css_foreground(transaction)
    if transaction.classifier
      if transaction.classifier.dark?
        "white"
      else
        "black"
      end
    else
      "black"
    end
  end
end

app/views/transactions/_approve.html.haml
= link_to t("transaction.symbol.#{transaction.approved ? 'approved' : 'unapproved'}"),
  "/transactions/#{transaction.id}/quick_approval_update",
  id: dom_id(transaction, :approve), class: "btn btn-sm approval-button",
  data: { turbo_method: :patch, turbo_stream: true }

app/views/transactions/_averages.html.haml
- if averages
  %p.text-center.mt-3
    - account = averages[:acct] ? t("transaction.accounts.#{averages[:acct]}") : t("any")
    = "#{averages[:name]} (#{account}),".html_safe
    - averages[:data].each_with_index do |a, i|
      = "#{a[0]}: <b>#{a[1]}</b>#{i + 1 < averages.length ? ', ' : ''}".html_safe

app/views/transactions/_t.html.haml
- style, color = classifier_style(t.classifier)
%tr
  %td.text-center= transaction_date(t.date)
  %td.text-center{style: style}= t.category
  %td{style: style}= t.description
  %td{style: style}= t.amount
  %td= t.balance
  %td= t("transaction.accounts.#{t.account}")
  %td.text-center
    - if t.classifier
      = link_to t("symbol.separator"), t.classifier, style: color, "data-turbo-frame" => "_top"
    - else
      = render "approve", transaction: t

app/views/transactions/index.html.haml
:ruby
  lo = Sni::Layout.call(
    lg: [[2,2,2],[2,2,2], [2,2,2]],
    md: [[3,3,3],[3,3,3], [3,3,3]],
    xs: [[4,4,4],[4,4,4], [4,4,4]],
  )
  inputs = [
    [:description,   t("transaction.description"), :text,   lo[0], size: 20, placeholder: t("transaction.description")],
    [:amount,        t("transaction.amount"),      :text,   lo[1], size: 20, placeholder: t("transaction.amount")],
    [:upload_id,     t("transaction.upload"),      :text,   lo[2], size: 20, placeholder: t("transaction.upload")],
    [:account,       t("transaction.account"),     :select, lo[3], menu: transaction_account_menu(params[:account])],
    [:category,      t("favourite.category"),      :select, lo[4], menu: transaction_category_menu(params[:category])],
    [:classifier_id, t("classifier.classifiers"),  :select, lo[5], menu: transaction_classifier_menu(params[:classifier_id])],
    [:date,          t("transaction.date"),        :text,   lo[6], size: 20, placeholder: t("transaction.date"), value: @corrections[:date] || params[:date]],
    [:days,          t("transaction.days"),        :text,   lo[7], size: 20, placeholder: t("transaction.days"), value: @corrections[:days] || params[:days]],
    [:order,         t("order"),                   :select, lo[8], menu: transaction_order_menu(params[:order])],
  ]

= render "utils/title", key: "transaction.transactions"

%section.mt-3
  .header
    .d-flex.justify-content-between.align-items-center
      %h3.mb-0= t("transaction.transactions")
      = link_to t("classifier.classifiers"), classifiers_path, class: "green-btn"
  .body
    = render "utils/search/form", index: transactions_path, inputs: inputs
    = turbo_frame_tag :results, "data-turbo-action" => "advance" do
      %div
        = render "averages", averages: @averages
      %div.d-none{
        "data-controller" => "correction",
        "data-correction-date-value" => @corrections[:date],
        "data-correction-days-value" => @corrections[:days],
        "data-correction-ulid-value" => @corrections[:ulid],
      }
      %table.table.table-bordered.table-sm.mt-3
        %thead
          %tr
            %th.text-center= t("transaction.date")
            %th.text-center= t("transaction.category")
            %th= t("transaction.description")
            %th= t("transaction.amount")
            %th= t("transaction.balance")
            %th= t("transaction.account")
            %th
        %tbody
          = render partial: "t", collection: @transactions.matches
          = render "utils/pagination_links", pager: @transactions, columns: 7

= form_with url: upload_transactions_path, multipart: true do |form|
  = form.file_field :file
  = form.submit t("transaction.analyse")

app/views/transactions/quick_approval_update.turbo_stream.haml
= turbo_stream.replace(dom_id(@transaction, :approve), partial: "approve", locals: { transaction: @transaction })